import { NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { normalizeRecipients,recipientLabel } from '@/lib/email-addresses';
import { cleanMailString } from '@/lib/email-encoding';

const esc=(value:string)=>value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));
const normalizeCid=(value:string)=>value.replace(/^<|>$/g,'').trim().toLowerCase();

export async function GET(request:Request,{params}:{params:Promise<{id:string}>}){
 const{id}=await params,row=db.prepare(`SELECT subject,sender_name senderName,sender_address senderAddress,recipients,received_at receivedAt,body_html bodyHtml,body_text bodyText,case_id caseId FROM emails WHERE id=?`).get(id)as{subject:string;senderName:string;senderAddress:string;recipients:string;receivedAt:string;bodyHtml:string;bodyText:string;caseId:string}|undefined;
 if(!row)return NextResponse.json({error:'E-Mail nicht gefunden.'},{status:404});
 const email={...row,subject:cleanMailString(row.subject),senderName:cleanMailString(row.senderName),senderAddress:cleanMailString(row.senderAddress),bodyHtml:cleanMailString(row.bodyHtml),bodyText:cleanMailString(row.bodyText)},recipients=normalizeRecipients(row.recipients),recipientRows=([['to','An'],['cc','Kopie'],['bcc','Blindkopie']]as const).map(([type,label])=>{const values=recipients.filter(item=>item.type===type);return values.length?`<dt>${label}</dt><dd>${values.map(item=>esc(recipientLabel(item))).join('<br>')}</dd>`:''}).join('');
 const attachments=db.prepare(`SELECT id,filename,size,content_type contentType,content_id contentId,is_inline isInline FROM attachments WHERE email_id=? ORDER BY filename`).all(id)as{id:string;filename:string;size:number;contentType:string;contentId:string;isInline:number}[];
 const inlineByCid=new Map(attachments.filter(item=>item.contentId).map(item=>[normalizeCid(item.contentId),item.id]));
 const visible=attachments.filter(item=>!item.isInline||!String(item.contentType||'').toLowerCase().startsWith('image/'));
 let body=email.bodyHtml||`<pre>${esc(email.bodyText||'')}</pre>`;
 body=body.replace(/cid:(?:&lt;|<)?([^"' >]+?)(?:&gt;|>)?(?=["' >])/gi,(match,cid:string)=>{
  const attachmentId=inlineByCid.get(normalizeCid(cid));
  return attachmentId?`/api/attachments/${encodeURIComponent(attachmentId)}?inline=1`:match;
 });
 const url=new URL(request.url),embed=url.searchParams.get('embed')==='1',allowExternal=url.searchParams.get('external')==='1',hasExternalImages=/\bsrc\s*=\s*["']https?:/i.test(body);
 const imageNotice=hasExternalImages?`<aside class="image-notice">${allowExternal?'Externe Bilder sind für diese Ansicht geladen.':'Externe Bilder sind zum Schutz vor Tracking gesperrt.'} <a target="_self" href="?${embed?'embed=1&':''}external=${allowExternal?'0':'1'}">${allowExternal?'Wieder sperren':'Einmalig anzeigen'}</a></aside>`:'';
 const meta=`<header class="mail-meta"><h1>${esc(email.subject)}</h1><dl><dt>Von</dt><dd><strong>${esc(email.senderName||email.senderAddress)}</strong>${email.senderName&&email.senderAddress?` &lt;${esc(email.senderAddress)}&gt;`:''}</dd>${recipientRows}<dt>Empfangen</dt><dd>${esc(new Intl.DateTimeFormat('de-DE',{dateStyle:'medium',timeStyle:'short'}).format(new Date(email.receivedAt)))}</dd><dt>Vorgang</dt><dd>${esc(email.caseId||'noch nicht zugeordnet')}</dd></dl></header>`;
 const files=`<section class="attachments"><h2>Anlagen <span>${visible.length}</span></h2>${visible.length?visible.map(file=>`<a href="/api/attachments/${encodeURIComponent(file.id)}"><span class="file-icon">▤</span><span><strong>${esc(file.filename)}</strong><small>${Math.max(1,Math.ceil(file.size/1024))} KB</small></span><b>Herunterladen</b></a>`).join(''):'<p>Keine separaten Anlagen</p>'}</section>`;
 const html=`<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(email.subject)}</title><base target="_blank"><style>
 :root{color-scheme:light}*{box-sizing:border-box}html{background:${embed?'#fff':'#eef3f0'}}body{margin:0;background:#fff;color:#202a25;font:15px/1.55 Arial,Helvetica,sans-serif;overflow-wrap:anywhere}${embed?'':'.shell{max-width:1060px;margin:28px auto;border:1px solid #dce5df;border-radius:12px;box-shadow:0 12px 40px rgba(24,55,43,.08);overflow:hidden}'}
 .mail-meta{padding:24px 28px 20px;border-bottom:1px solid #e1e8e4;background:#fbfcfb}.mail-meta h1{margin:0 0 17px;color:#17231e;font:600 24px/1.25 Georgia,serif}.mail-meta dl{display:grid;grid-template-columns:88px minmax(0,1fr);gap:6px 12px;margin:0;font-size:12px}.mail-meta dt{color:#748179}.mail-meta dd{margin:0;color:#34423b}
 .image-notice{padding:9px 14px;border-bottom:1px solid #eadba9;background:#fff9e8;color:#735d16;font-size:11px}.image-notice a{color:#176247;font-weight:bold}.message{min-height:260px;padding:28px;overflow:auto}.message>table{max-width:100%}.message img{max-width:100%;height:auto}.message pre{margin:0;white-space:pre-wrap;font:14px/1.6 ui-monospace,SFMono-Regular,Consolas,monospace}.message a{color:#126548}.message blockquote{margin-left:12px;padding-left:16px;border-left:3px solid #dbe5df;color:#526159}
 .attachments{padding:21px 28px 28px;border-top:1px solid #e1e8e4;background:#fbfcfb}.attachments h2{margin:0 0 12px;font-size:14px}.attachments h2 span{display:inline-grid;place-items:center;min-width:22px;height:22px;margin-left:6px;border-radius:11px;background:#e2eee7;color:#176247;font-size:11px}.attachments>a{display:grid;grid-template-columns:34px minmax(0,1fr) auto;gap:10px;align-items:center;padding:11px 12px;border:1px solid #dde6e1;border-radius:8px;background:#fff;color:#26352e;text-decoration:none}.attachments>a+a{margin-top:8px}.attachments>a:hover{border-color:#9fc2b1;background:#f5faf7}.attachments strong,.attachments small{display:block}.attachments small,.attachments>p{margin:2px 0 0;color:#7a8780;font-size:11px}.attachments>a>b{color:#176247;font-size:11px}.file-icon{color:#176247;font-size:20px}
 @media(max-width:680px){.shell{margin:0;border:0;border-radius:0}.mail-meta,.message,.attachments{padding-left:18px;padding-right:18px}.mail-meta dl{grid-template-columns:1fr}.mail-meta dt{margin-top:5px}.attachments>a>b{display:none}}
 </style></head><body><div class="shell">${embed?'':meta}${imageNotice}<main class="message">${body}</main>${embed?'':files}</div></body></html>`;
 return new NextResponse(html,{headers:{'content-type':'text/html; charset=utf-8','content-security-policy':`default-src 'none'; style-src 'unsafe-inline'; img-src 'self' data:${allowExternal?' https: http:':''}; frame-ancestors 'self'; base-uri 'self'; form-action 'none'; connect-src 'none'; script-src 'none'`,'referrer-policy':'no-referrer','x-content-type-options':'nosniff'}});
}
