'use client';
/* eslint-disable react-hooks/exhaustive-deps */
import { FormEvent,useEffect,useRef,useState } from 'react';
import MarketPartnerPicker from '@/components/MarketPartnerPicker';
type CaseData={id:string;title:string;category:string;partner:string;marketPartnerId:string;market:string;location:string;meterNumber:string;owner:string;dueDate:string;status:string;priority:string;description:string;process:string;processReference:string;checkIdentifier:string;nextAction:string;handoverSummary:string;rootCause:string;targetResolution:string;counterpartContact:string;counterpartEmail:string;escalationLevel:string;lastContactAt:string;tags:string;ruleMode:string;exceptionReason:string;referenceDate:string;deadlineType:string;deadlineSource:string;closedAt:string;closureVerifiedBy:string;updatedAt:string};
type Activity={id:number;kind:string;text:string;author:string;createdAt:string};type Task={id:string;text:string;done:number;owner:string;dueDate:string};type Asset={id:string;filename:string;contentType:string;size:number;kind:string;createdAt:string};type Check={id:string;label:string;status:'open'|'done'|'not_applicable';required:number;note:string;source:string};type Analysis={timeline:{id:string;filename:string;messageType:string;version:string;sender:string;receiver:string;createdAt:string}[];valueGroups:Record<string,{document:string;type:string;value:string;unit:string}[]>;warnings:string[];notice:string};
const statuses=['Neu','In Prüfung','Rückfrage NB','Warten auf MSB','Warten auf Lieferant','Gelöst'],priorities=['Niedrig','Mittel','Hoch','Kritisch'],processes=['WiM – Werte','WiM – Gerätewechsel','GPKE – Zuordnung / Lieferantenwechsel','GeLi Gas – Zuordnung / Lieferantenwechsel','Stammdatenänderung','Netznutzungsabrechnung','Mehr-/Mindermengen','Bilanzierung','Marktkommunikation / APERAK','Historischer / freier Clearingfall'];
const fmt=(value:string)=>new Intl.DateTimeFormat('de-DE',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value));
export default function CaseWorkspace({caseId,onClose,onChanged}:{caseId:string;onClose:()=>void;onChanged:()=>Promise<void>}){
 const[item,setItem]=useState<CaseData|null>(null),[activities,setActivities]=useState<Activity[]>([]),[tasks,setTasks]=useState<Task[]>([]),[checks,setChecks]=useState<Check[]>([]),[checkDraft,setCheckDraft]=useState(''),[closingIssues,setClosingIssues]=useState<string[]>([]),[analysis,setAnalysis]=useState<Analysis|null>(null),[files,setFiles]=useState<Asset[]>([]),[emails,setEmails]=useState<Asset[]>([]),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[dragging,setDragging]=useState(false),fileInput=useRef<HTMLInputElement>(null);
 const load=async()=>{const[detail,assets,analysisResponse]=await Promise.all([fetch(`/api/cases?id=${caseId}`),fetch(`/api/cases/${caseId}/files`),fetch(`/api/cases/${caseId}/analysis`)]),data=await detail.json(),assetData=await assets.json(),analysisData=await analysisResponse.json();if(detail.ok){setItem(data.case);setActivities(data.activities);setTasks(data.tasks);setChecks(data.checks);setClosingIssues(data.closingIssues)}if(assets.ok){setFiles(assetData.files);setEmails(assetData.emails)}if(analysisResponse.ok)setAnalysis(analysisData)};
 useEffect(()=>{const start=async()=>{await load()};void start()},[caseId]);
 const save=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setSaving(true);const response=await fetch('/api/cases',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:caseId,...Object.fromEntries(new FormData(event.currentTarget))})}),data=await response.json();setMessage(response.ok?'Vorgang gespeichert.':`${data.error||'Speichern fehlgeschlagen.'}${data.issues?.length?` ${data.issues.join(' · ')}`:''}`);if(response.ok)await Promise.all([load(),onChanged()]);setSaving(false)};
 const addNote=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=event.currentTarget;await fetch('/api/cases',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:caseId,...Object.fromEntries(new FormData(form))})});form.reset();await load()};
 const addTask=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=event.currentTarget;await fetch(`/api/cases/${caseId}/tasks`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(form)))});form.reset();await load()};
 const toggleTask=async(task:Task)=>{await fetch(`/api/cases/${caseId}/tasks`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({taskId:task.id,done:!task.done})});await load()};
 const updateCheck=async(check:Check,status:Check['status'])=>{let note=check.note;if(status==='not_applicable'&&!note)note=window.prompt('Warum ist dieser Prüfschritt für den Vorgang nicht anwendbar?')||'';const response=await fetch(`/api/cases/${caseId}/checks`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({checkId:check.id,status,note})});if(response.ok)await load();else setMessage((await response.json()).error||'Prüfschritt konnte nicht geändert werden.')};
 const addCheck=async()=>{if(!checkDraft.trim())return;await fetch(`/api/cases/${caseId}/checks`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({label:checkDraft})});setCheckDraft('');await load()};
 const upload=async(list:FileList|File[])=>{for(const file of Array.from(list)){const form=new FormData();form.set('file',file);await fetch(`/api/cases/${caseId}/files`,{method:'POST',body:form})}await load()};
 if(!item)return <div className="case-workspace"><div className="case-loading">Vorgang wird geladen …</div></div>;
 return <div className="case-workspace"><header className="case-workspace-head"><button className="back-button" onClick={onClose}>← Arbeitsvorrat</button><div><p className="eyebrow">{item.id} · zuletzt geändert {fmt(item.updatedAt)}</p><h1>{item.title}</h1><p>{item.partner} · {item.location}</p></div><div className="case-head-status"><a className="export-button" href={`/api/cases/${caseId}/export`} target="_blank">Vorgang exportieren</a><span className={`priority priority-${item.priority.toLowerCase()}`}>{item.priority}</span><span className="status">{item.status}</span></div></header>
 <form className="case-editor" onSubmit={save}><main>
  <section className="case-brief"><div className="section-title"><div><p className="eyebrow">Übergabe und Wiedereinstieg</p><h2>Was ist hier gerade los?</h2></div><span>Für Vertretung und nächsten Arbeitstag</span></div><textarea name="handoverSummary" rows={5} defaultValue={item.handoverSummary} placeholder="Ausgangslage, Prüfstand, Rückfragen und aktueller Wartepunkt"/><div className="next-action"><label>Nächste konkrete Aktion<input name="nextAction" defaultValue={item.nextAction}/></label><label>Wiedervorlage<input name="dueDate" type="date" defaultValue={item.dueDate}/></label></div></section>
  <section className="case-section"><div className="section-title"><div><p className="eyebrow">Fachliche Bearbeitung</p><h2>Sachverhalt und Lösung</h2></div></div><div className="editor-grid"><label className="wide">Titel<input name="title" defaultValue={item.title}/></label><label className="wide">Ausgangssachverhalt<textarea name="description" rows={5} defaultValue={item.description}/></label><label>Ermittelte Ursache<textarea name="rootCause" rows={4} defaultValue={item.rootCause}/></label><label>Lösung und verifiziertes Ergebnis<textarea name="targetResolution" rows={4} defaultValue={item.targetResolution}/></label></div></section>
  <section className="case-section"><div className="section-title"><div><p className="eyebrow">Fachliche Prüfliste</p><h2>Was wurde geprüft?</h2></div><strong>{checks.filter(check=>check.status==='open').length} offen</strong></div><div className="check-list">{checks.map(check=><article key={check.id} className={check.status}><button type="button" onClick={()=>updateCheck(check,check.status==='done'?'open':'done')}>{check.status==='done'?'✓':check.status==='not_applicable'?'–':'○'}</button><div><b>{check.label}{Boolean(check.required)&&<em>Pflicht</em>}</b>{check.note&&<small>{check.note}</small>}</div><button type="button" className="na-button" onClick={()=>updateCheck(check,'not_applicable')}>nicht anwendbar</button></article>)}</div><div className="inline-check-add"><input value={checkDraft} onChange={event=>setCheckDraft(event.target.value)} placeholder="Individuellen Prüfschritt ergänzen …"/><button type="button" className="secondary" onClick={addCheck}>Hinzufügen</button></div></section>
  <section className="case-section"><div className="section-title"><div><p className="eyebrow">Nachrichtenkette und Vergleich</p><h2>EDIFACT-Prüfhilfe</h2></div><span>{analysis?.timeline.length||0} Dokumente</span></div>{analysis?.warnings.map((warning,index)=><p className="analysis-warning" key={index}>{warning}</p>)}{analysis&&analysis.timeline.length>0&&<div className="process-timeline">{analysis.timeline.map(document=><article key={document.id}><span>{document.messageType}</span><div><b>{document.filename}</b><small>{document.sender||'–'} → {document.receiver||'–'} · {fmt(document.createdAt)} · Version {document.version||'–'}</small></div></article>)}</div>}{analysis&&Object.entries(analysis.valueGroups).map(([group,values])=><div className="value-compare" key={group}><h3>{group}</h3>{values.map((value,index)=><p key={index}><span>{value.type} · {value.document}</span><b>{value.value} {value.unit}</b></p>)}</div>)}<small className="analysis-notice">{analysis?.notice}</small></section>
  <section className="case-section"><div className="section-title"><div><p className="eyebrow">Offene Punkte</p><h2>To-dos im Vorgang</h2></div><strong>{tasks.filter(task=>!task.done).length} offen</strong></div><div className="task-list">{tasks.map(task=><button type="button" key={task.id} className={task.done?'done':''} onClick={()=>toggleTask(task)}><span>{task.done?'✓':'○'}</span><span><b>{task.text}</b><small>{task.owner}{task.dueDate?` · fällig ${new Intl.DateTimeFormat('de-DE').format(new Date(`${task.dueDate}T12:00:00`))}`:''}</small></span></button>)}</div></section>
  <section className="case-section"><div className="section-title"><div><p className="eyebrow">Nachweise</p><h2>E-Mails, Screenshots und Dokumente</h2></div><button type="button" className="secondary" onClick={()=>fileInput.current?.click()}>Datei auswählen</button></div><input ref={fileInput} hidden multiple type="file" accept=".msg,.eml,image/*,.pdf,.txt,.csv,.xls,.xlsx" onChange={e=>e.target.files&&upload(e.target.files)}/><div className={`drop-zone case-work-drop ${dragging?'dragging':''}`} onDragEnter={e=>{e.preventDefault();setDragging(true)}} onDragOver={e=>e.preventDefault()} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);upload(e.dataTransfer.files)}}><span>＋</span><div><b>E-Mail, Screenshot oder Datei ablegen</b><p>Die Ablage wird diesem Vorgang zugeordnet und im Journal protokolliert.</p></div></div><div className="workspace-assets">{emails.map(asset=><a href={`/api/emails/view/${asset.id}`} target="_blank" key={asset.id}><span>✉</span><b>{asset.filename}</b></a>)}{files.map(asset=><a href={`/api/case-files/${asset.id}`} target="_blank" key={asset.id}><span>{asset.contentType.startsWith('image/')?'▧':'▤'}</span><b>{asset.filename}</b></a>)}</div></section>
  <section className="case-section history-section"><div className="section-title"><div><p className="eyebrow">Nachvollziehbarkeit</p><h2>Journal und Kommunikation</h2></div></div><div className="case-history">{activities.map(activity=><article key={activity.id}><span className={`activity-icon ${activity.kind}`}>{activity.kind==='phone'?'☎':activity.kind==='email'?'✉':'✓'}</span><div><p>{activity.text}</p><small>{activity.author} · {fmt(activity.createdAt)}</small></div></article>)}</div></section>
 </main><aside>
  <section className="case-side-card"><h3>Steuerung</h3><label>Status<select name="status" defaultValue={item.status}>{statuses.map(value=><option key={value}>{value}</option>)}</select></label><label>Priorität<select name="priority" defaultValue={item.priority}>{priorities.map(value=><option key={value}>{value}</option>)}</select></label><label>Bearbeitung<input name="owner" defaultValue={item.owner}/></label><label>Eskalation<select name="escalationLevel" defaultValue={item.escalationLevel}><option>Keine</option><option>Teamleitung</option><option>Marktpartner-Management</option><option>Regulatorisch kritisch</option></select></label></section>
  <section className="case-side-card rule-card"><h3>Regelwerk und Altfall</h3><label>Bearbeitungsmodus<select name="ruleMode" defaultValue={item.ruleMode}><option value="standard">Standard – Prüfungen verbindlich</option><option value="flexible">Flexibel – begründete Abweichung</option><option value="historical">Historisch – Altfall / alte Marktlage</option></select></label><label>Fachliches Bezugsdatum<input name="referenceDate" type="date" defaultValue={item.referenceDate}/></label><label>Ausnahme- / Altfallbegründung<textarea name="exceptionReason" rows={3} defaultValue={item.exceptionReason}/></label><p>Maßgeblich bleibt die zum Bezugsdatum gültige Vorgabe.</p></section>
  <section className="case-side-card"><h3>Friststeuerung</h3><label>Fristart<select name="deadlineType" defaultValue={item.deadlineType}><option>Interne Wiedervorlage</option><option>Erwartete Marktpartnerantwort</option><option>Prozessfrist</option><option>Individuelle Vereinbarung</option><option>Historischer Zieltermin</option></select></label><label>Fristquelle<input name="deadlineSource" defaultValue={item.deadlineSource} placeholder="AHB/Prozess, E-Mail, interne Vorgabe …"/></label></section>
  <section className="case-side-card"><h3>Prozessbezug</h3><label>Prozess<input name="process" list="process-list" defaultValue={item.process}/><datalist id="process-list">{processes.map(value=><option key={value}>{value}</option>)}</datalist></label><label>Prozess-/Nachrichtenreferenz<input name="processReference" defaultValue={item.processReference}/></label><label>Prüfidentifikator<input name="checkIdentifier" defaultValue={item.checkIdentifier}/></label><label>Tags<input name="tags" defaultValue={item.tags}/></label></section>
  <section className="case-side-card"><h3>Identifikation</h3><div className="partner-form-field"><span>Marktpartner</span><MarketPartnerPicker initialName={item.partner} initialId={item.marketPartnerId}/></div><label>Sparte<select name="market" defaultValue={item.market}><option>Strom</option><option>Gas</option></select></label><label>MaLo / MeLo<input name="location" defaultValue={item.location}/></label><label>Zählernummer<input name="meterNumber" defaultValue={item.meterNumber}/></label><label>Fallart<input name="category" defaultValue={item.category}/></label></section>
  <section className="case-side-card"><h3>Ansprechpartner</h3><label>Name<input name="counterpartContact" defaultValue={item.counterpartContact}/></label><label>E-Mail<input name="counterpartEmail" type="email" defaultValue={item.counterpartEmail}/></label><label>Letzter Kontakt<input name="lastContactAt" type="datetime-local" defaultValue={item.lastContactAt?.slice(0,16)}/></label></section>
  {closingIssues.length>0&&<section className="case-side-card closing-card"><h3>Vor dem Abschluss</h3>{closingIssues.map(issue=><p key={issue}>○ {issue}</p>)}</section>}<button className="primary save-case" disabled={saving}>{saving?'Speichert …':'Änderungen speichern'}</button>{message&&<output className={`save-message ${message.includes('fehl')||message.includes('erforderlich')?'error':''}`}>{message}</output>}
 </aside></form><div className="case-bottom-tools"><form onSubmit={addTask}><input name="text" required placeholder="Offenen Punkt hinzufügen …"/><input name="dueDate" type="date"/><button className="secondary">＋ Aufgabe</button></form><form onSubmit={addNote}><select name="noteKind"><option value="note">Interne Notiz</option><option value="phone">Telefonat</option><option value="email">E-Mail / Rückmeldung</option><option value="decision">Entscheidung</option></select><input name="note" required placeholder="Was wurde besprochen, geprüft oder entschieden?"/><button className="primary">Dokumentieren</button></form></div></div>
}
