'use client';
import { useEffect,useState } from 'react';

type CaseData={id:string;title:string;category:string;partner:string;market:string;location:string;meterNumber:string;dueDate:string;description:string};
type Partner={name:string;email:string};
function texts(item:CaseData){const facts=`Vorgang: ${item.id}\nSparte: ${item.market}\nMaLo / MeLo: ${item.location}\nZählernummer: ${item.meterNumber||'nicht angegeben'}`;return[
 {name:'Klärungsanfrage',subject:`Klärung ${item.id}: ${item.title}`,body:`Guten Tag,\n\nbitte prüfen Sie folgenden Sachverhalt und geben Sie uns eine Rückmeldung:\n\n${facts}\n\nSachverhalt:\n${item.description||item.title}\n\nVielen Dank.\n\nMit freundlichen Grüßen`},
 {name:'Messwert anfordern',subject:`Fehlender bzw. abweichender Messwert – ${item.id}`,body:`Guten Tag,\n\nzu der unten genannten Lokation liegt uns kein plausibler beziehungsweise ein abweichender Zählerstand vor. Bitte prüfen Sie den Messwert einschließlich Ablesezeitpunkt und Übermittlung.\n\n${facts}\n\nBitte teilen Sie uns den korrekten Stand, das Ablesedatum und die Ableseart mit.\n\nMit freundlichen Grüßen`},
 {name:'Stammdaten klären',subject:`Stammdatenklärung – ${item.id}`,body:`Guten Tag,\n\nbei der Zuordnung der folgenden Lokation bestehen abweichende Stammdaten:\n\n${facts}\n\nBitte prüfen Sie insbesondere Gerätezuordnung, Gültigkeitszeitraum und Marktrollen-Zuordnung und senden Sie uns die korrekten Daten.\n\nMit freundlichen Grüßen`},
 {name:'Erinnerung',subject:`Erinnerung zu unserer Klärungsanfrage ${item.id}`,body:`Guten Tag,\n\nzu unserer Klärungsanfrage haben wir noch keine abschließende Rückmeldung erhalten.\n\n${facts}\n\nWir bitten um Rückmeldung bis zum ${new Intl.DateTimeFormat('de-DE').format(new Date(`${item.dueDate}T12:00:00`))}.\n\nVielen Dank.\n\nMit freundlichen Grüßen`}
]}
export default function MailTemplates({item}:{item:CaseData}){
 const templates=texts(item),[template,setTemplate]=useState(0),[subject,setSubject]=useState(()=>templates[0].subject),[body,setBody]=useState(()=>templates[0].body),[partner,setPartner]=useState<Partner|null>(null),[copied,setCopied]=useState(false),[open,setOpen]=useState(false);
 useEffect(()=>{const find=async()=>{const response=await fetch(`/api/market-partners?name=${encodeURIComponent(item.partner)}`),data=await response.json();setPartner(response.ok?(data.partners.find((entry:Partner)=>entry.name.toLowerCase()===item.partner.toLowerCase())||data.partners[0]||null):null)};void find()},[item.partner]);
 const select=(index:number)=>{setTemplate(index);setSubject(templates[index].subject);setBody(templates[index].body);setCopied(false)};
 const copy=async()=>{const value=`Betreff: ${subject}\n\n${body}`;try{if(!navigator.clipboard)throw new Error('Clipboard API nicht verfügbar');await navigator.clipboard.writeText(value)}catch{const area=document.createElement('textarea');area.value=value;area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.focus();area.select();document.execCommand('copy');area.remove()}setCopied(true)};
 const mailto=`mailto:${encodeURIComponent(partner?.email||'')}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
 return <><button className="mail-template-launcher" onClick={()=>setOpen(value=>!value)}>✉ Mailvorlage</button>{open&&<section className="detail-card mail-templates"><div className="card-title"><div><h3>Mailvorlage für {item.id}</h3><p>{partner?.email?`Empfänger aus Marktpartnerstamm: ${partner.email}`:'Keine E-Mail-Adresse im Marktpartnerstamm gefunden.'}</p></div><button className="template-close" onClick={()=>setOpen(false)}>×</button></div><select className="template-select" value={template} onChange={e=>select(Number(e.target.value))}>{templates.map((entry,index)=><option value={index} key={entry.name}>{entry.name}</option>)}</select><label>Betreff<input value={subject} onChange={e=>setSubject(e.target.value)}/></label><label>Text<textarea rows={12} value={body} onChange={e=>setBody(e.target.value)}/></label><div className="template-actions"><button className="secondary" onClick={copy}>{copied?'Kopiert ✓':'Betreff & Text kopieren'}</button><a className="primary" href={mailto}>Im E-Mail-Programm öffnen</a></div><small className="template-hint">Es wird nichts automatisch versendet. Vor dem Versand bitte fachlich prüfen.</small></section>}</>
}
