'use client';
import { KeyboardEvent,useEffect,useId,useRef,useState } from 'react';

type Partner={id:string;externalId:string;name:string;marketRole:string;bdewCode:string;gln:string;email:string;city:string};

export default function MarketPartnerPicker({initialName='',initialId='',required=false}:{initialName?:string;initialId?:string;required?:boolean}){
 const[query,setQuery]=useState(initialName),[selectedId,setSelectedId]=useState(initialId),[partners,setPartners]=useState<Partner[]>([]),[open,setOpen]=useState(false),[loading,setLoading]=useState(false),[active,setActive]=useState(-1),root=useRef<HTMLDivElement>(null),resultsId=useId();
 useEffect(()=>{const close=(event:MouseEvent)=>{if(!root.current?.contains(event.target as Node))setOpen(false)};document.addEventListener('mousedown',close);return()=>document.removeEventListener('mousedown',close)},[]);
 useEffect(()=>{if(!open)return;const controller=new AbortController(),timer=window.setTimeout(async()=>{setLoading(true);try{const response=await fetch(`/api/market-partners?q=${encodeURIComponent(query.trim())}`,{signal:controller.signal}),data=await response.json();if(response.ok){setPartners(data.partners.slice(0,30));setActive(-1)}}catch(error){if(!(error instanceof DOMException&&error.name==='AbortError'))setPartners([])}finally{if(!controller.signal.aborted)setLoading(false)}},180);return()=>{window.clearTimeout(timer);controller.abort()}},[query,open]);
 const select=(partner:Partner)=>{setQuery(partner.name);setSelectedId(partner.id);setOpen(false);setActive(-1)};
 const keyDown=(event:KeyboardEvent<HTMLInputElement>)=>{if(event.key==='ArrowDown'){event.preventDefault();setOpen(true);setActive(value=>Math.min(value+1,partners.length-1))}else if(event.key==='ArrowUp'){event.preventDefault();setActive(value=>Math.max(value-1,0))}else if(event.key==='Enter'&&open&&active>=0){event.preventDefault();select(partners[active])}else if(event.key==='Escape')setOpen(false)};
 return <div className="market-partner-picker" ref={root}><input type="hidden" name="partner" value={query.trim()}/><input type="hidden" name="marketPartnerId" value={selectedId}/><div className={`partner-picker-input ${open?'open':''}`}><span>⌕</span><input value={query} required={required} autoComplete="off" role="combobox" aria-controls={resultsId} aria-expanded={open} aria-autocomplete="list" placeholder="Name, Navision-Nr., BDEW-Code oder GLN suchen …" onFocus={()=>setOpen(true)} onKeyDown={keyDown} onChange={event=>{setQuery(event.target.value);setSelectedId('');setOpen(true)}}/>{selectedId&&<button type="button" title="Auswahl lösen" onClick={()=>{setSelectedId('');setQuery('');setOpen(true)}}>×</button>}</div>{open&&<div className="partner-picker-results" id={resultsId} role="listbox">{loading?<p>Marktpartner werden gesucht …</p>:partners.length?partners.map((partner,index)=><button type="button" role="option" aria-selected={partner.id===selectedId} className={index===active?'active':''} key={partner.id} onMouseDown={event=>event.preventDefault()} onClick={()=>select(partner)}><b>{partner.name}</b><span>{[partner.externalId&&`Navision ${partner.externalId}`,partner.marketRole,partner.bdewCode||partner.gln,partner.city].filter(Boolean).join(' · ')||'Keine weiteren Stammdaten'}</span></button>):<p>{query.trim()?'Kein Marktpartner gefunden. Freie Eingabe bleibt möglich.':'Noch keine Marktpartner vorhanden.'}</p>}</div>}{selectedId&&<small className="partner-selected">✓ Mit Marktpartnerstamm verknüpft</small>}</div>
}
