import iconv from 'iconv-lite';

export type CsvDecoding={text:string;encoding:'UTF-8'|'Windows-1252'|'DOS/OEM 850'|'UTF-16 LE'|'UTF-16 BE';repaired:boolean};
const cp1252Special=new Map<string,number>([['€',0x80],['‚',0x82],['ƒ',0x83],['„',0x84],['…',0x85],['†',0x86],['‡',0x87],['ˆ',0x88],['‰',0x89],['Š',0x8a],['‹',0x8b],['Œ',0x8c],['Ž',0x8e],['‘',0x91],['’',0x92],['“',0x93],['”',0x94],['•',0x95],['–',0x96],['—',0x97],['˜',0x98],['™',0x99],['š',0x9a],['›',0x9b],['œ',0x9c],['ž',0x9e],['Ÿ',0x9f]]);
const cp1252Undefined=[0x81,0x8d,0x8f,0x90,0x9d];
const oemControlRepair=new Map(cp1252Undefined.map(byte=>[String.fromCharCode(byte),iconv.decode(Buffer.from([byte]),'cp850')]));
function stripBom(value:string){return value.replace(/^\uFEFF/,'')}
function mojibakeScore(value:string){return(value.match(/Ã.|Â.|â.|ð.|\uFFFD/g)||[]).length}
function tryRepair(value:string){const bytes:number[]=[];for(const char of value){const code=char.codePointAt(0)!;if(cp1252Special.has(char))bytes.push(cp1252Special.get(char)!);else if(code<=0xff)bytes.push(code);else return null}try{const repaired=new TextDecoder('utf-8',{fatal:true}).decode(Uint8Array.from(bytes));return mojibakeScore(repaired)<mojibakeScore(value)?repaired:null}catch{return null}}
export function repairMojibake(value:string){const oemRepaired=value.replace(/[\u0081\u008d\u008f\u0090\u009d]/g,char=>oemControlRepair.get(char)||char);if(!mojibakeScore(oemRepaired))return oemRepaired;const complete=tryRepair(oemRepaired);if(complete)return complete;return oemRepaired.split(/([;,\t\r\n])/).map(part=>tryRepair(part)||part).join('')}
function looksUtf16(buffer:Buffer,littleEndian:boolean){if(buffer.length<4)return false;let zeros=0,samples=0;for(let i=littleEndian?1:0;i<Math.min(buffer.length,4000);i+=2){samples++;if(buffer[i]===0)zeros++}return samples>0&&zeros/samples>.3}
function decodeUtf16Be(buffer:Buffer){const copy=Buffer.from(buffer);for(let i=0;i+1<copy.length;i+=2){const first=copy[i];copy[i]=copy[i+1];copy[i+1]=first}return copy.toString('utf16le')}
export function decodeCsvWithInfo(buffer:Buffer):CsvDecoding{let text:string,encoding:CsvDecoding['encoding'];if(buffer[0]===0xff&&buffer[1]===0xfe){text=buffer.subarray(2).toString('utf16le');encoding='UTF-16 LE'}else if(buffer[0]===0xfe&&buffer[1]===0xff){text=decodeUtf16Be(buffer.subarray(2));encoding='UTF-16 BE'}else if(looksUtf16(buffer,true)){text=buffer.toString('utf16le');encoding='UTF-16 LE'}else if(looksUtf16(buffer,false)){text=decodeUtf16Be(buffer);encoding='UTF-16 BE'}else{try{text=new TextDecoder('utf-8',{fatal:true}).decode(buffer);encoding='UTF-8'}catch{if(cp1252Undefined.some(byte=>buffer.includes(byte))){text=iconv.decode(buffer,'cp850');encoding='DOS/OEM 850'}else{text=new TextDecoder('windows-1252').decode(buffer);encoding='Windows-1252'}}}text=stripBom(text);const repaired=repairMojibake(text);return{text:repaired,encoding,repaired:repaired!==text}}
export function decodeCsv(buffer:Buffer){return decodeCsvWithInfo(buffer).text}
function count(line:string,char:string){let quoted=false,total=0;for(let i=0;i<line.length;i++){if(line[i]==='"')quoted=!quoted;else if(!quoted&&line[i]===char)total++}return total}
export function parseCsv(text:string){const first=text.split(/\r?\n/,1)[0]||'',delimiter=[';',',','\t'].sort((a,b)=>count(first,b)-count(first,a))[0],rows:string[][]=[];let row:string[]=[],field='',quoted=false;for(let i=0;i<text.length;i++){const char=text[i];if(char==='"'){if(quoted&&text[i+1]==='"'){field+='"';i++}else quoted=!quoted}else if(char===delimiter&&!quoted){row.push(field.trim());field=''}else if((char==='\n'||char==='\r')&&!quoted){if(char==='\r'&&text[i+1]==='\n')i++;row.push(field.trim());if(row.some(Boolean))rows.push(row);row=[];field=''}else field+=char}row.push(field.trim());if(row.some(Boolean))rows.push(row);return{delimiter,headers:rows[0]||[],rows:rows.slice(1)}}
export function normalizeHeader(value:string){return value.toLowerCase().replaceAll('ä','ae').replaceAll('ö','oe').replaceAll('ü','ue').replaceAll('ß','ss').replace(/[^a-z0-9]/g,'')}
