import Database from 'better-sqlite3';
import fs from 'node:fs';
import path from 'node:path';

const dataDir=process.env.DATA_DIR||path.join(process.cwd(),'data');
fs.mkdirSync(dataDir,{recursive:true});
fs.mkdirSync(path.join(dataDir,'attachments'),{recursive:true});
const globalDb=globalThis as typeof globalThis&{__netzklaerungDb?:Database.Database};
export const db=globalDb.__netzklaerungDb??new Database(path.join(dataDir,'netzklaerung.sqlite'));
if(process.env.NODE_ENV!=='production')globalDb.__netzklaerungDb=db;
db.pragma('journal_mode = WAL'); db.pragma('foreign_keys = ON'); db.pragma('busy_timeout = 5000');
db.exec(`
CREATE TABLE IF NOT EXISTS cases (id TEXT PRIMARY KEY,title TEXT NOT NULL,category TEXT NOT NULL,partner TEXT NOT NULL,market TEXT NOT NULL,location TEXT NOT NULL,meter_number TEXT,owner TEXT NOT NULL,due_date TEXT NOT NULL,status TEXT NOT NULL,priority TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY,username TEXT NOT NULL UNIQUE,display_name TEXT NOT NULL,email TEXT,role TEXT NOT NULL DEFAULT 'user',password_hash TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS case_tasks (id TEXT PRIMARY KEY,case_id TEXT NOT NULL,text TEXT NOT NULL,done INTEGER NOT NULL DEFAULT 0,owner TEXT,due_date TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(case_id) REFERENCES cases(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS activities (id INTEGER PRIMARY KEY AUTOINCREMENT,case_id TEXT NOT NULL,kind TEXT NOT NULL,text TEXT NOT NULL,author TEXT NOT NULL,created_at TEXT NOT NULL,FOREIGN KEY(case_id) REFERENCES cases(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS emails (id TEXT PRIMARY KEY,graph_id TEXT UNIQUE,internet_message_id TEXT,subject TEXT NOT NULL,sender_name TEXT,sender_address TEXT,recipients TEXT,received_at TEXT NOT NULL,body_html TEXT,body_text TEXT,has_attachments INTEGER NOT NULL DEFAULT 0,case_id TEXT,source TEXT NOT NULL DEFAULT 'outlook',created_at TEXT NOT NULL,FOREIGN KEY(case_id) REFERENCES cases(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS attachments (id TEXT PRIMARY KEY,email_id TEXT,filename TEXT NOT NULL,content_type TEXT,size INTEGER NOT NULL DEFAULT 0,storage_path TEXT NOT NULL,edifact_document_id TEXT,created_at TEXT NOT NULL,FOREIGN KEY(email_id) REFERENCES emails(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS case_files (id TEXT PRIMARY KEY,case_id TEXT NOT NULL,filename TEXT NOT NULL,content_type TEXT,size INTEGER NOT NULL DEFAULT 0,storage_path TEXT NOT NULL,kind TEXT NOT NULL DEFAULT 'file',created_at TEXT NOT NULL,FOREIGN KEY(case_id) REFERENCES cases(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS market_partners (id TEXT PRIMARY KEY,external_id TEXT,name TEXT NOT NULL,market_role TEXT,bdew_code TEXT,gln TEXT,email TEXT,phone TEXT,street TEXT,postal_code TEXT,city TEXT,source TEXT NOT NULL DEFAULT 'csv',raw_json TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS edifact_documents (id TEXT PRIMARY KEY,filename TEXT NOT NULL,message_type TEXT NOT NULL,version TEXT,sender TEXT,receiver TEXT,reference TEXT,raw_text TEXT NOT NULL,parsed_json TEXT NOT NULL,validation_json TEXT NOT NULL DEFAULT '[]',email_id TEXT,case_id TEXT,created_at TEXT NOT NULL,FOREIGN KEY(email_id) REFERENCES emails(id) ON DELETE SET NULL,FOREIGN KEY(case_id) REFERENCES cases(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS case_checks (id TEXT PRIMARY KEY,case_id TEXT NOT NULL,label TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'open',required INTEGER NOT NULL DEFAULT 0,note TEXT NOT NULL DEFAULT '',source TEXT NOT NULL DEFAULT 'manual',sort_order INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(case_id) REFERENCES cases(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS inbox_decisions (item_type TEXT NOT NULL,item_id TEXT NOT NULL,decision TEXT NOT NULL,note TEXT NOT NULL DEFAULT '',decided_by TEXT NOT NULL,decided_at TEXT NOT NULL,PRIMARY KEY(item_type,item_id));
CREATE TABLE IF NOT EXISTS app_state (key TEXT PRIMARY KEY,value TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_cases_status_due ON cases(status,due_date); CREATE INDEX IF NOT EXISTS idx_cases_partner ON cases(partner); CREATE INDEX IF NOT EXISTS idx_activities_case ON activities(case_id,created_at); CREATE INDEX IF NOT EXISTS idx_case_checks_case ON case_checks(case_id,sort_order); CREATE INDEX IF NOT EXISTS idx_case_files_case ON case_files(case_id,created_at DESC); CREATE INDEX IF NOT EXISTS idx_emails_received ON emails(received_at DESC); CREATE INDEX IF NOT EXISTS idx_edifact_type ON edifact_documents(message_type,created_at DESC); CREATE INDEX IF NOT EXISTS idx_market_partners_name ON market_partners(name); CREATE INDEX IF NOT EXISTS idx_market_partners_external ON market_partners(external_id); CREATE INDEX IF NOT EXISTS idx_market_partners_bdew ON market_partners(bdew_code);
`);
const caseColumns=db.prepare('PRAGMA table_info(cases)').all()as{name:string}[];
for(const[column,definition]of Object.entries({process:"TEXT NOT NULL DEFAULT ''",process_reference:"TEXT NOT NULL DEFAULT ''",check_identifier:"TEXT NOT NULL DEFAULT ''",next_action:"TEXT NOT NULL DEFAULT ''",handover_summary:"TEXT NOT NULL DEFAULT ''",root_cause:"TEXT NOT NULL DEFAULT ''",target_resolution:"TEXT NOT NULL DEFAULT ''",counterpart_contact:"TEXT NOT NULL DEFAULT ''",counterpart_email:"TEXT NOT NULL DEFAULT ''",escalation_level:"TEXT NOT NULL DEFAULT 'Keine'",last_contact_at:"TEXT NOT NULL DEFAULT ''",tags:"TEXT NOT NULL DEFAULT ''",rule_mode:"TEXT NOT NULL DEFAULT 'flexible'",exception_reason:"TEXT NOT NULL DEFAULT ''",reference_date:"TEXT NOT NULL DEFAULT ''",deadline_type:"TEXT NOT NULL DEFAULT 'Interne Wiedervorlage'",deadline_source:"TEXT NOT NULL DEFAULT ''",closed_at:"TEXT NOT NULL DEFAULT ''",closure_verified_by:"TEXT NOT NULL DEFAULT ''",market_partner_id:"TEXT NOT NULL DEFAULT ''"}))if(!caseColumns.some(item=>item.name===column))try{db.exec(`ALTER TABLE cases ADD COLUMN ${column} ${definition}`)}catch(error){if(!(error instanceof Error)||!error.message.includes('duplicate column'))throw error}
for(const[table,column]of[['emails','content_hash'],['edifact_documents','content_hash']]as const){const columns=db.prepare(`PRAGMA table_info(${table})`).all()as{name:string}[];if(!columns.some(item=>item.name===column))try{db.exec(`ALTER TABLE ${table} ADD COLUMN ${column} TEXT NOT NULL DEFAULT ''`)}catch(error){if(!(error instanceof Error)||!error.message.includes('duplicate column'))throw error}}
db.exec(`CREATE INDEX IF NOT EXISTS idx_emails_hash ON emails(content_hash); CREATE INDEX IF NOT EXISTS idx_edifact_hash ON edifact_documents(content_hash);`);
export function getState(key:string){return(db.prepare('SELECT value FROM app_state WHERE key=?').get(key)as{value:string}|undefined)?.value}
export function setState(key:string,value:string){db.prepare(`INSERT INTO app_state(key,value,updated_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at`).run(key,value,new Date().toISOString())}
export function attachmentDir(emailId:string){const safe=emailId.replace(/[^a-zA-Z0-9_-]/g,'_'),dir=path.join(dataDir,'attachments',safe);fs.mkdirSync(dir,{recursive:true});return dir}
export function caseFileDir(caseId:string){const safe=caseId.replace(/[^a-zA-Z0-9_-]/g,'_'),dir=path.join(dataDir,'cases',safe);fs.mkdirSync(dir,{recursive:true});return dir}
export function safeFilename(value:string){return path.basename(value).replace(/[^a-zA-Z0-9._äöüÄÖÜß-]/g,'_').slice(0,180)||'anlage.bin'}
export function removeStoredFiles(storagePaths:string[]){const root=`${path.resolve(/* turbopackIgnore: true */dataDir)}${path.sep}`;let removed=0;for(const storagePath of storagePaths){const resolved=path.resolve(/* turbopackIgnore: true */storagePath);if(!resolved.startsWith(root))continue;try{if(fs.existsSync(resolved)){fs.unlinkSync(resolved);removed++}}catch{/* Der Datenbankeintrag ist gelöscht; verwaiste Dateien können administrativ bereinigt werden. */}}return removed}
