export type Separators={component:string;element:string;decimal:string;release:string;repetition:string;segment:string};
export type ParsedSegment={tag:string;name:string;description:string;elements:string[][];raw:string};
export type ParsedMessage={reference:string;type:string;typeLabel:string;version:string;documentCode:string;documentReference:string;summary:Record<string,unknown>;segments:ParsedSegment[]};
export type ParsedEdifact={syntax:string;sender:string;receiver:string;interchangeReference:string;separators:Separators;messages:ParsedMessage[];validation:{level:'info'|'warning'|'error';text:string}[]};

export const messageTypes:Record<string,string>={
 APERAK:'Anwendungsfehler und Bestätigung',COMDIS:'Handelsunstimmigkeit',CONTRL:'Syntaxprüfung und Empfangsbestätigung',IFTSTA:'Statusbericht',INSRPT:'Prüfbericht',INVOIC:'Rechnung',MSCONS:'Messwerte und Energiemengen',ORDCHG:'Bestelländerung',ORDERS:'Bestellung / Prozessanforderung',ORDRSP:'Bestellantwort',PARTIN:'Partnerstammdaten',PRICAT:'Preisliste / Katalog',QUOTES:'Angebot',REQOTE:'Anfrage',REMADV:'Zahlungsavis',UTILMD:'Stammdaten zu Markt- und Messlokationen',UTILTS:'Netznutzungszeiten',GASDAT:'Gasbeschaffenheitsdaten',UTILTS_XML:'Netznutzungszeiten (XML)',UNKNOWN:'Unbekannter Nachrichtentyp'
};
const segmentNames:Record<string,string>={UNA:'Servicezeichen',UNB:'Nutzdaten-Kopf',UNH:'Nachrichten-Kopf',UNT:'Nachrichten-Ende',UNZ:'Nutzdaten-Ende',BGM:'Dokumentbeginn',DTM:'Datum / Zeit / Zeitraum',RFF:'Referenz',NAD:'Marktpartner / Beteiligter',LOC:'Lokation',IDE:'Geschäftsvorgang',STS:'Status / Antwortgrund',QTY:'Menge / Messwert',MEA:'Messgröße',PIA:'Produkt- oder Gerätekennung',CCI:'Merkmal',CAV:'Merkmalswert',SEQ:'Sequenz / Datenbereich',LIN:'Position',PRI:'Preis',MOA:'Geldbetrag',TAX:'Steuer',FTX:'Freitext',ERC:'Fehlercode',DOC:'Dokument',CNT:'Kontrollsumme',COM:'Kommunikationsverbindung'};
const qualifier:Record<string,string>={
 '9':'Nachrichten-/Dokumentdatum','137':'Dokumentdatum','163':'Beginn','164':'Ende','Z01':'Marktlokation','Z02':'Messlokation','Z03':'Netzlokation','Z16':'zugeordnete Marktlokation','Z19':'Messlokation','Z30':'Gerätenummer','Z31':'alte Gerätenummer','Z36':'MaLo-ID','Z37':'MeLo-ID','Z38':'Netzlokations-ID','Z39':'Technische Ressourcen-ID','Z40':'Steuerbare Ressourcen-ID','24':'Geschäftsvorgang','MR':'Nachrichtenempfänger','MS':'Nachrichtensender','DP':'Lieferstelle','SU':'Lieferant','BY':'Kunde','IV':'Rechnungsempfänger','5':'Messwert','46':'gelieferte Menge','47':'Verbrauchsmenge','67':'Zählerstand','220':'Zählerstand','Z10':'Arbeit / Energie','Z11':'Leistung','KWH':'Kilowattstunde','KWT':'Kilowatt','MTQ':'Kubikmeter','DAY':'Tag','MON':'Monat','HUR':'Stunde','E01':'bestätigt','E02':'abgelehnt','Z14':'nicht plausibel','Z20':'Fristüberschreitung','Z33':'fehlende Daten'};
function label(value:string){return qualifier[value]||value}
function splitEscaped(value:string,separator:string,release:string){const out:string[]=[];let current='';for(let i=0;i<value.length;i++){const c=value[i];if(c===release&&i+1<value.length){current+=value[++i];continue}if(c===separator){out.push(current);current=''}else current+=c}out.push(current);return out}
function describe(tag:string,e:string[][]){const one=(i:number,j=0)=>e[i]?.[j]||'';switch(tag){case'UNB':return `Übertragung von ${one(1)} an ${one(2)} · Referenz ${one(4)}`;case'UNH':return `${messageTypes[one(1)]||one(1)} · Referenz ${one(0)}`;case'BGM':return `${label(one(0))}${one(1)?` · Dokument ${one(1)}`:''}`;case'DTM':return `${label(one(0))}: ${one(0,1)||one(1)}${one(0,2)?` (Format ${one(0,2)})`:''}`;case'RFF':return `${label(one(0))}: ${one(0,1)}`;case'NAD':return `${label(one(0))}: ${one(1)}`;case'LOC':return `${label(one(0))}: ${one(1)}`;case'QTY':return `${label(one(0))}: ${one(0,1)} ${label(one(0,2))}`;case'MEA':return `${label(one(0))}: ${e.flat().slice(1).map(label).join(' · ')}`;case'STS':return `Status: ${e.flat().map(label).join(' · ')}`;case'ERC':return `Fehler: ${e.flat().map(label).join(' · ')}`;case'CCI':return `Merkmal: ${e.flat().map(label).join(' · ')}`;case'CAV':return `Wert: ${e.flat().map(label).join(' · ')}`;case'UNT':return `${one(0)} Segmente · Nachrichtenreferenz ${one(1)}`;case'UNZ':return `${one(0)} Nachricht(en) · Übertragungsreferenz ${one(1)}`;default:return e.flat().filter(Boolean).map(label).join(' · ')}}
function parseSegment(raw:string,separators:Separators):ParsedSegment{const parts=splitEscaped(raw,separators.element,separators.release),tag=parts.shift()?.trim()||'',elements=parts.map(p=>splitEscaped(p,separators.component,separators.release));return{tag,name:segmentNames[tag]||'EDIFACT-Segment',description:describe(tag,elements),elements,raw}}
function formatDate(value:string,format:string){if(format==='102'&&/^\d{8}$/.test(value))return`${value.slice(6,8)}.${value.slice(4,6)}.${value.slice(0,4)}`;if(format==='203'&&/^\d{12}$/.test(value))return`${value.slice(6,8)}.${value.slice(4,6)}.${value.slice(0,4)} ${value.slice(8,10)}:${value.slice(10,12)}`;return value}
function summarize(segments:ParsedSegment[]){const locations:unknown[]=[],references:unknown[]=[],values:unknown[]=[],dates:unknown[]=[],parties:unknown[]=[],statuses:unknown[]=[],attributes:unknown[]=[];for(const s of segments){const e=s.elements;if(s.tag==='LOC')locations.push({art:label(e[0]?.[0]||''),id:e[1]?.[0]||''});if(s.tag==='RFF')references.push({art:label(e[0]?.[0]||''),wert:e[0]?.[1]||''});if(s.tag==='QTY')values.push({art:label(e[0]?.[0]||''),wert:e[0]?.[1]||'',einheit:label(e[0]?.[2]||'')});if(s.tag==='DTM')dates.push({art:label(e[0]?.[0]||''),wert:formatDate(e[0]?.[1]||'',e[0]?.[2]||'')});if(s.tag==='NAD')parties.push({rolle:label(e[0]?.[0]||''),id:e[1]?.[0]||''});if(s.tag==='STS'||s.tag==='ERC')statuses.push(s.description);if(s.tag==='CCI'||s.tag==='CAV')attributes.push(s.description)}return{locations,references,values,dates,parties,statuses,attributes}}
export function parseEdifact(input:string):ParsedEdifact{let raw=input.replace(/^\uFEFF/,'').trim(),separators:Separators={component:':',element:'+',decimal:'.',release:'?',repetition:'*',segment:"'"};if(raw.startsWith('UNA')&&raw.length>=9){separators={component:raw[3],element:raw[4],decimal:raw[5],release:raw[6],repetition:raw[7],segment:raw[8]};raw=raw.slice(9)}const rawSegments=splitEscaped(raw,separators.segment,separators.release).map(x=>x.replace(/[\r\n]/g,'').trim()).filter(Boolean),segments=rawSegments.map(x=>parseSegment(x,separators)),unb=segments.find(x=>x.tag==='UNB'),unz=segments.find(x=>x.tag==='UNZ'),sender=unb?.elements[1]?.[0]||'',receiver=unb?.elements[2]?.[0]||'',interchangeReference=unb?.elements[4]?.[0]||'',validation:ParsedEdifact['validation']=[];if(!unb)validation.push({level:'error',text:'UNB-Segment fehlt – kein vollständiger EDIFACT-Nutzdatenrahmen.'});if(!unz)validation.push({level:'error',text:'UNZ-Segment fehlt – Übertragung ist möglicherweise abgeschnitten.'});const messages:ParsedMessage[]=[];let current:ParsedSegment[]=[];for(const s of segments){if(s.tag==='UNH')current=[s];else if(current.length){current.push(s);if(s.tag==='UNT'){const unh=current[0],bgm=current.find(x=>x.tag==='BGM'),type=unh.elements[1]?.[0]||'UNKNOWN',declared=Number(s.elements[0]?.[0]||0);if(declared&&declared!==current.length)validation.push({level:'warning',text:`Nachricht ${unh.elements[0]?.[0]}: UNT meldet ${declared} Segmente, gelesen wurden ${current.length}.`});messages.push({reference:unh.elements[0]?.[0]||'',type,typeLabel:messageTypes[type]||messageTypes.UNKNOWN,version:unh.elements[1]?.slice(1).filter(Boolean).join('.')||'',documentCode:bgm?.elements[0]?.[0]||'',documentReference:bgm?.elements[1]?.[0]||'',summary:summarize(current),segments:current});current=[]}}}if(!messages.length&&segments.length)validation.push({level:'warning',text:'Keine vollständige UNH/UNT-Nachricht erkannt. Die Segmente werden dennoch angezeigt.'});if(unz&&messages.length&&Number(unz.elements[0]?.[0])!==messages.length)validation.push({level:'warning',text:`UNZ meldet ${unz.elements[0]?.[0]} Nachricht(en), erkannt wurden ${messages.length}.`});validation.unshift({level:'info',text:`${messages.length} Nachricht(en), ${segments.length} Segmente, Sender ${sender||'unbekannt'}, Empfänger ${receiver||'unbekannt'}.`});return{syntax:unb?.elements[0]?.join(':')||'UNOC:3',sender,receiver,interchangeReference,separators,messages:messages.length?messages:[{reference:'',type:'UNKNOWN',typeLabel:messageTypes.UNKNOWN,version:'',documentCode:'',documentReference:'',summary:summarize(segments),segments}],validation}}
export function looksLikeEdifact(filename:string,content:string){return/\.(edi|edifact|txt|dat)$/i.test(filename)||/(^|[\r\n])UNA.{6}UNB|(^|[\r\n])UNB[+:]/.test(content.slice(0,500))}
