import { createHash,randomUUID } from 'node:crypto';
import MsgReader from '@kenjiuno/msgreader';
import { simpleParser } from 'mailparser';
import { db,safeFilename } from './db';
import { normalizeRecipients } from './email-addresses';
import { isInlineAttachment } from './email-attachments';
import { cleanMailString,decodeMsgHtml } from './email-encoding';
import { mailText,sanitizeMailHtml } from './email-html';
import { linkCase,saveAttachment } from './store-document';

function mime(filename:string){const ext=filename.split('.').pop()?.toLowerCase();return({png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',gif:'image/gif',webp:'image/webp',pdf:'application/pdf',txt:'text/plain',csv:'text/csv',xml:'application/xml',edi:'application/edifact'}as Record<string,string>)[ext||'']||'application/octet-stream'}
function insert(input:{subject:string;senderName:string;senderAddress:string;recipients:unknown[];receivedAt:string;bodyHtml:string;bodyText:string;caseId:string|null;source:string;attachmentCount:number;contentHash:string}){const existing=db.prepare('SELECT id,case_id caseId FROM emails WHERE content_hash=? LIMIT 1').get(input.contentHash)as{id:string;caseId:string|null}|undefined;if(existing){db.prepare(`UPDATE emails SET subject=?,sender_name=?,sender_address=?,recipients=?,received_at=?,body_html=?,body_text=?,has_attachments=?,case_id=COALESCE(?,case_id),source=? WHERE id=?`).run(input.subject,input.senderName,input.senderAddress,JSON.stringify(input.recipients),input.receivedAt,input.bodyHtml,input.bodyText,input.attachmentCount?1:0,input.caseId,input.source,existing.id);return{ id:existing.id,duplicate:true }}const id=randomUUID(),now=new Date().toISOString();db.prepare(`INSERT INTO emails(id,graph_id,internet_message_id,subject,sender_name,sender_address,recipients,received_at,body_html,body_text,has_attachments,case_id,source,created_at,content_hash) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,null,'',input.subject,input.senderName,input.senderAddress,JSON.stringify(input.recipients),input.receivedAt,input.bodyHtml,input.bodyText,input.attachmentCount?1:0,input.caseId,input.source,now,input.contentHash);return{id,duplicate:false}}
function repairAttachment(emailId:string,filename:string,contentId?:string,inline?:boolean){db.prepare(`UPDATE attachments SET content_id=?,is_inline=? WHERE email_id=? AND filename=?`).run((contentId||'').replace(/^<|>$/g,'').trim(),inline?1:0,emailId,safeFilename(filename))}
export async function importEmailBuffer(buffer:Buffer,filename:string,forcedCaseId?:string){
 const contentHash=createHash('sha256').update(buffer).digest('hex');
 if(/\.msg$/i.test(filename)){
  const arrayBuffer=buffer.buffer.slice(buffer.byteOffset,buffer.byteOffset+buffer.byteLength)as ArrayBuffer,reader=new MsgReader(arrayBuffer);reader.parserConfig={ansiEncoding:'windows1252'};const info=reader.getFileData();
  if(info.error)throw new Error(`MSG konnte nicht gelesen werden: ${info.error}`);
  const html=info.bodyHtml?cleanMailString(info.bodyHtml):decodeMsgHtml(info.html,info.internetCodepage||info.messageCodepage),text=cleanMailString(info.body)||mailText(html),subject=cleanMailString(info.subject)||filename,caseId=forcedCaseId||linkCase(`${subject}\n${text}`),attachments=info.attachments||[],inline=(item:typeof attachments[number])=>{const filename=item.fileName||'anlage.bin';return isInlineAttachment({contentType:item.attachMimeTag||mime(filename),declaredInline:item.attachmentHidden,contentId:item.pidContentId,html})},inserted=insert({subject,senderName:cleanMailString(info.senderName),senderAddress:cleanMailString(info.senderSmtpAddress||info.sentRepresentingSmtpAddress||info.senderEmail),recipients:normalizeRecipients(info.recipients||[]),receivedAt:new Date(info.messageDeliveryTime||info.clientSubmitTime||info.creationTime||Date.now()).toISOString(),bodyHtml:sanitizeMailHtml(html),bodyText:text,caseId,source:'msg-drop',attachmentCount:attachments.filter(item=>!inline(item)).length,contentHash}),id=inserted.id;
  if(inserted.duplicate){for(const item of attachments)repairAttachment(id,item.fileName||'anlage.bin',item.pidContentId,inline(item));return{id,attachments:0,caseId,duplicate:true,repaired:true}}
  for(const item of attachments){const attachment=reader.getAttachment(item),attachmentName=attachment.fileName||item.fileName||'anlage.bin';saveAttachment({emailId:id,filename:attachmentName,contentType:item.attachMimeTag||mime(attachmentName),buffer:Buffer.from(attachment.content),contentId:item.pidContentId,inline:inline(item)})}
  return{id,attachments:attachments.filter(item=>!inline(item)).length,caseId,duplicate:false};
 }
 if(!/\.eml$/i.test(filename))throw new Error('Unterstützt werden Outlook-Nachrichten als .msg oder .eml.');
 const parsed=await simpleParser(buffer,{keepCidLinks:true}),html=typeof parsed.html==='string'?sanitizeMailHtml(cleanMailString(parsed.html)):'',text=cleanMailString(parsed.text),addressList=(value:typeof parsed.to,type:'to'|'cc'|'bcc')=>(Array.isArray(value)?value:value?[value]:[]).flatMap(item=>item.value.map(address=>({...address,type}))),recipients=normalizeRecipients([...addressList(parsed.to,'to'),...addressList(parsed.cc,'cc'),...addressList(parsed.bcc,'bcc')]),subject=cleanMailString(parsed.subject)||filename,caseId=forcedCaseId||linkCase(`${subject}\n${text}`),inline=(item:typeof parsed.attachments[number])=>isInlineAttachment({contentType:item.contentType,declaredInline:item.related,contentId:item.contentId||item.cid,html}),visibleAttachments=parsed.attachments.filter(item=>!inline(item)),inserted=insert({subject,senderName:cleanMailString(parsed.from?.value[0]?.name),senderAddress:cleanMailString(parsed.from?.value[0]?.address),recipients,receivedAt:(parsed.date||new Date()).toISOString(),bodyHtml:html,bodyText:text,caseId,source:'eml-drop',attachmentCount:visibleAttachments.length,contentHash}),id=inserted.id;
 if(inserted.duplicate){for(const attachment of parsed.attachments)repairAttachment(id,attachment.filename||'anlage.bin',attachment.contentId||attachment.cid,inline(attachment));return{id,attachments:0,caseId,duplicate:true,repaired:true}}
 for(const attachment of parsed.attachments)saveAttachment({emailId:id,filename:attachment.filename||'anlage.bin',contentType:attachment.contentType,buffer:attachment.content,contentId:attachment.contentId||attachment.cid,inline:inline(attachment)});
 return{id,attachments:visibleAttachments.length,caseId,duplicate:false};
}
