import { randomUUID } from 'node:crypto';
import { db,getState,setState } from './db';
import { normalizeRecipients } from './email-addresses';
import { isInlineAttachment } from './email-attachments';
import { cleanMailString } from './email-encoding';
import { mailText,sanitizeMailHtml } from './email-html';
import { linkCase,saveAttachment } from './store-document';

const cfg=()=>({tenant:process.env.MS_TENANT_ID||'',client:process.env.MS_CLIENT_ID||'',secret:process.env.MS_CLIENT_SECRET||'',mailbox:process.env.OUTLOOK_MAILBOX||'',folder:process.env.OUTLOOK_FOLDER_ID||'inbox'});
export function outlookStatus(){const c=cfg();return{configured:Boolean(c.tenant&&c.client&&c.secret&&c.mailbox),mailbox:c.mailbox||null,folder:c.folder,lastSync:getState('outlook_last_sync')||null}}
async function token(){const c=cfg();if(!c.tenant||!c.client||!c.secret)throw new Error('Microsoft-Graph-Zugangsdaten fehlen.');const body=new URLSearchParams({client_id:c.client,client_secret:c.secret,scope:'https://graph.microsoft.com/.default',grant_type:'client_credentials'}),res=await fetch(`https://login.microsoftonline.com/${encodeURIComponent(c.tenant)}/oauth2/v2.0/token`,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body});if(!res.ok)throw new Error(`Microsoft-Anmeldung fehlgeschlagen (${res.status}).`);return((await res.json())as{access_token:string}).access_token}
async function graph(url:string,accessToken:string){const res=await fetch(url,{headers:{authorization:`Bearer ${accessToken}`,'prefer':'odata.maxpagesize=50'}});if(!res.ok)throw new Error(`Microsoft Graph antwortet mit ${res.status}: ${(await res.text()).slice(0,240)}`);return res.json()as Promise<Record<string,unknown>>}
type GraphRecipient={emailAddress?:{name?:string;address?:string};type?:'to'|'cc'|'bcc'};
type GraphMessage={id:string;internetMessageId?:string;subject?:string;from?:{emailAddress?:{name?:string;address?:string}};toRecipients?:GraphRecipient[];ccRecipients?:GraphRecipient[];bccRecipients?:GraphRecipient[];receivedDateTime?:string;body?:{contentType?:string;content?:string};bodyPreview?:string;hasAttachments?:boolean;isRead?:boolean};
async function importAttachments(message:GraphMessage,localId:string,accessToken:string){if(!message.hasAttachments)return 0;const c=cfg(),url=`https://graph.microsoft.com/v1.0/users/${encodeURIComponent(c.mailbox)}/messages/${encodeURIComponent(message.id)}/attachments?$select=id,name,contentType,size,isInline,contentId,contentBytes`,payload=await graph(url,accessToken),items=(payload.value||[])as{['@odata.type']?:string;name?:string;contentType?:string;isInline?:boolean;contentId?:string;contentBytes?:string}[];let count=0;for(const item of items){if(!item.contentBytes||item['@odata.type']!=='#microsoft.graph.fileAttachment')continue;const inline=isInlineAttachment({contentType:item.contentType,declaredInline:item.isInline,contentId:item.contentId,html:message.body?.content});saveAttachment({emailId:localId,filename:item.name||'anlage.bin',contentType:item.contentType,buffer:Buffer.from(item.contentBytes,'base64'),contentId:item.contentId,inline});if(!inline)count++}return count}
async function upsertMessage(message:GraphMessage,accessToken:string){const existing=db.prepare('SELECT id FROM emails WHERE graph_id=?').get(message.id)as{id:string}|undefined,localId=existing?.id||randomUUID(),content=cleanMailString(message.body?.content||message.bodyPreview),isHtml=message.body?.contentType?.toLowerCase()==='html',safeHtml=isHtml?sanitizeMailHtml(content):'',bodyText=isHtml?mailText(content):content,subject=cleanMailString(message.subject)||'(ohne Betreff)',combined=`${subject}\n${bodyText}`,caseId=linkCase(combined),recipients=normalizeRecipients([...(message.toRecipients||[]).map(item=>({...item,type:'to'})),...(message.ccRecipients||[]).map(item=>({...item,type:'cc'})),...(message.bccRecipients||[]).map(item=>({...item,type:'bcc'}))]),now=new Date().toISOString();db.prepare(`INSERT INTO emails(id,graph_id,internet_message_id,subject,sender_name,sender_address,recipients,received_at,body_html,body_text,has_attachments,case_id,source,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(graph_id) DO UPDATE SET subject=excluded.subject,sender_name=excluded.sender_name,sender_address=excluded.sender_address,recipients=excluded.recipients,received_at=excluded.received_at,body_html=excluded.body_html,body_text=excluded.body_text,has_attachments=excluded.has_attachments,case_id=COALESCE(excluded.case_id,emails.case_id)`).run(localId,message.id,message.internetMessageId||'',subject,cleanMailString(message.from?.emailAddress?.name),cleanMailString(message.from?.emailAddress?.address),JSON.stringify(recipients),message.receivedDateTime||now,safeHtml,bodyText,message.hasAttachments?1:0,caseId,'outlook',now);if(!existing)await importAttachments(message,localId,accessToken);return existing?0:1}
export async function syncOutlook(){const c=cfg();if(!outlookStatus().configured)throw new Error('Outlook ist noch nicht konfiguriert.');const accessToken=await token(),deltaKey='outlook_delta_link_recipients_v2',savedDelta=getState(deltaKey),select='$select=id,internetMessageId,subject,from,toRecipients,ccRecipients,bccRecipients,receivedDateTime,body,bodyPreview,hasAttachments,isRead',base=`https://graph.microsoft.com/v1.0/users/${encodeURIComponent(c.mailbox)}/mailFolders/${encodeURIComponent(c.folder)}/messages/delta?${select}&$orderby=receivedDateTime%20desc`,initialSince=new Date(Date.now()-30*864e5).toISOString(),start=savedDelta||`${base}&$filter=receivedDateTime%20ge%20${initialSince}`;let url=start,pages=0,imported=0,seen=0,delta='';while(url&&pages<30){const payload=await graph(url,accessToken),items=(payload.value||[])as GraphMessage[];for(const item of items){if((item as GraphMessage&{'@removed'?:unknown})['@removed'])continue;seen++;imported+=await upsertMessage(item,accessToken)}url=(payload['@odata.nextLink']as string)||'';delta=(payload['@odata.deltaLink']as string)||delta;pages++}if(delta)setState(deltaKey,delta);const finished=new Date().toISOString();setState('outlook_last_sync',finished);return{imported,seen,pages,lastSync:finished}}
