import fs from 'node:fs';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import { db,attachmentDir,safeFilename } from './db';
import { looksLikeEdifact,parseEdifact } from './edifact';

export function linkCase(text:string){const caseMatch=text.match(/VG-\d{4}-\d{4}/i)?.[0],caseRow=caseMatch?db.prepare('SELECT id FROM cases WHERE id=?').get(caseMatch):undefined;if(caseRow)return(caseRow as{id:string}).id;const location=text.match(/DE\d{12,35}/)?.[0];if(location){const row=db.prepare('SELECT id FROM cases WHERE location=?').get(location)as{id:string}|undefined;return row?.id||null}return null}
export function saveAttachment(input:{emailId?:string;filename:string;contentType?:string;buffer:Buffer}){const id=randomUUID(),emailId=input.emailId||'manual',filename=safeFilename(input.filename),dir=attachmentDir(emailId),storagePath=path.join(dir,`${id}-${filename}`);fs.writeFileSync(storagePath,input.buffer);let edifactDocumentId:string|undefined;const text=input.buffer.toString('utf8');if(looksLikeEdifact(filename,text)){edifactDocumentId=saveEdifact({filename,raw:text,emailId:input.emailId})}db.prepare(`INSERT INTO attachments(id,email_id,filename,content_type,size,storage_path,edifact_document_id,created_at) VALUES(?,?,?,?,?,?,?,?)`).run(id,input.emailId||null,filename,input.contentType||'application/octet-stream',input.buffer.length,storagePath,edifactDocumentId||null,new Date().toISOString());return{id,filename,edifactDocumentId}}
export function saveEdifact(input:{filename:string;raw:string;emailId?:string}){const parsed=parseEdifact(input.raw),first=parsed.messages[0],id=randomUUID(),caseId=linkCase(input.raw);db.prepare(`INSERT INTO edifact_documents(id,filename,message_type,version,sender,receiver,reference,raw_text,parsed_json,validation_json,email_id,case_id,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,safeFilename(input.filename),first?.type||'UNKNOWN',first?.version||'',parsed.sender,parsed.receiver,first?.reference||parsed.interchangeReference,input.raw,JSON.stringify(parsed),JSON.stringify(parsed.validation),input.emailId||null,caseId,new Date().toISOString());return id}
