import { randomUUID } from 'node:crypto';
import { NextRequest,NextResponse } from 'next/server';
import { requestUser } from '@/lib/auth';
import { db } from '@/lib/db';
import { hashPassword } from '@/lib/password';
function admin(request:NextRequest){return requestUser(request)?.role==='admin'}
export async function GET(request:NextRequest){if(!admin(request))return NextResponse.json({error:'Keine Berechtigung.'},{status:403});const users=db.prepare(`SELECT id,username,display_name displayName,email,role,active,created_at createdAt FROM users ORDER BY active DESC,display_name`).all();return NextResponse.json({users})}
export async function POST(request:NextRequest){if(!admin(request))return NextResponse.json({error:'Keine Berechtigung.'},{status:403});const body=await request.json()as{username?:string;displayName?:string;email?:string;role?:string;password?:string};if(!body.username?.trim()||!body.displayName?.trim()||(body.password?.length||0)<10)return NextResponse.json({error:'Pflichtfelder fehlen oder Passwort ist kürzer als 10 Zeichen.'},{status:400});try{const id=randomUUID(),now=new Date().toISOString();db.prepare(`INSERT INTO users(id,username,display_name,email,role,password_hash,active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)`).run(id,body.username.trim().toLowerCase(),body.displayName.trim(),body.email?.trim()||'',body.role==='admin'?'admin':'user',hashPassword(body.password!),1,now,now);return NextResponse.json({id},{status:201})}catch{return NextResponse.json({error:'Benutzername ist bereits vergeben.'},{status:409})}}
export async function PATCH(request:NextRequest){if(!admin(request))return NextResponse.json({error:'Keine Berechtigung.'},{status:403});const body=await request.json()as{id?:string;displayName?:string;email?:string;role?:string;active?:boolean;password?:string};if(!body.id)return NextResponse.json({error:'Benutzer-ID fehlt.'},{status:400});const fields:string[]=[],values:unknown[]=[];if(body.displayName){fields.push('display_name=?');values.push(body.displayName.trim())}if(body.email!==undefined){fields.push('email=?');values.push(body.email.trim())}if(body.role){fields.push('role=?');values.push(body.role==='admin'?'admin':'user')}if(body.active!==undefined){fields.push('active=?');values.push(body.active?1:0)}if(body.password){if(body.password.length<10)return NextResponse.json({error:'Passwort ist kürzer als 10 Zeichen.'},{status:400});fields.push('password_hash=?');values.push(hashPassword(body.password))}if(!fields.length)return NextResponse.json({error:'Keine Änderung übergeben.'},{status:400});fields.push('updated_at=?');values.push(new Date().toISOString(),body.id);db.prepare(`UPDATE users SET ${fields.join(',')} WHERE id=?`).run(...values);return NextResponse.json({ok:true})}
